### ISSUE TITLE
add repo for base24 version?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [joeyschoblaska/catppuccin-base16#2]
as per the [base24 style guide](https://github.com/tinted-theming/base24/blob/master/styling.md), this could be done by per flavor mapping the [catppuccin colors](https://github.com/catppuccin/catppuccin) like:

```yaml
# as before
base00: base
base01: mantle
base02: surface0
base03: surface1
base04: surface2
base05: text
base06: rosewater
base07: lavender
base08: red
base09: peach
base0A: yellow
base0B: green
base0C: teal
base0D: blue
base0E: mauve
base0F: flamingo
# new
base10: mantle # darker background
base11: crust # darkest background
base12: maroon # bright red
base13: rosewater # bright yellow
base14: green # bright green
base15: sky # bright cyan
base16: sapphire # bright blue
base17: pink # bright purple
```

i've added comments describing the role of the new items in base24.
note this mapping reuses catppuccin colors `mantle`, `rosewater` and `green`, each of which had a role in the base16 mapping already as well.
a few catppuccin colors remain unused in this mapping:

- `Subtext1`
- `Subtext0`
- `Overlay2`
- `Overlay1`
- `Overlay0`
